name: Build sdks and push to release branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HOSPITALITY_API_DOCS_DIR: hospitality-api-docs
      HOSPITALITY_API_DOCS_BRANCH: property_23.2.0.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout hospitality-api-docs
        uses: actions/checkout@v3
        with:
          repository: oracle/hospitality-api-docs
          path: ${{ env.HOSPITALITY_API_DOCS_DIR }}
          ref: ${{ env.HOSPITALITY_API_DOCS_BRANCH }}

      - name: Checkout to release branch
        run: git checkout -b "release_${{ env.HOSPITALITY_API_DOCS_BRANCH }}"

      - uses: actions/setup-node@v3
        timeout-minutes: 2
        with:
          node-version: 20

      - name: Install deps
        run: yarn install

      - name: Build sdks
        run: yarn build

      - name: Get hospitality-api-docs's commit sha
        id: ohip_docs
        run: echo "commit_sha=$(git --git-dir=${{ env.HOSPITALITY_API_DOCS_DIR }}/.git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Remove dist from gitignore
        run: sed -i '/dist/d' ./.gitignore

      - name: Push release files to release branch
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dist/**/*
          git commit -m 'generated sdks for release' --quiet
          git push --set-upstream origin "release_${{ env.HOSPITALITY_API_DOCS_BRANCH }}"
